apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-mcp-staging
  namespace: argocd
  labels:
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MessagePolly/mcp-clickhouse.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: "staging"
        - name: image.repository
          value: "820976530109.dkr.ecr.ap-southeast-1.amazonaws.com/clickhouse-mcp"
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
