apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clickhouse-mcp.fullname" . }}
  labels:
    {{- include "clickhouse-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clickhouse-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "clickhouse-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clickhouse-mcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # ClickHouse secrets (managed by Terraform via External Secrets Operator)
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse-mcp.fullname" $ }}-secret
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse-mcp.fullname" $ }}-secret
                  key: CLICKHOUSE_PORT
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse-mcp.fullname" $ }}-secret
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse-mcp.fullname" $ }}-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse-mcp.fullname" $ }}-secret
                  key: CLICKHOUSE_DB
          {{- if .Values.readinessCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessCheck.path }}
              port: {{ .Values.readinessCheck.port }}
            initialDelaySeconds: {{ .Values.readinessCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessCheck.timeoutSeconds }}
            successThreshold: {{ .Values.readinessCheck.successThreshold }}
            failureThreshold: {{ .Values.readinessCheck.failureThreshold }}
          {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
